create table if not exists genres
(
    id   int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists users
(
    id       int generated by default as identity primary key,
    name     varchar(255),
    login    varchar(255) not null,
    birthday date         not null,
    email    varchar(255) not null
);


create table if not exists mpas
(
    id   int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists films
(
    id           int generated by default as identity primary key,
    name         varchar(255) not null,
    release_date date,
    description  varchar(200),
    duration     int,
    rate         int
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   INT NOT NULL,
    friend_id INT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);




